# Generated by Django 3.0.4 on 2020-03-31 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20200331_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firtname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('date_of_death', models.DateTimeField(blank=True, null=True, verbose_name='death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(help_text='enter describtion', max_length=1000)),
                ('isbn', models.CharField(help_text='13 character', max_length=13, verbose_name='isbn')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstanse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for this', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=300)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'maintenance'), ('o', 'onload'), ('a', 'availble'), ('r', 'reserved')], default='m', help_text='book availble', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='select genre', to='app.genre'),
        ),
    ]
