# Generated by Django 3.0.4 on 2020-03-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
